#GUI OF EMAIL BOMBER
#AMLAN SAHA KUNDU
#GUI VERSION 1.0
#PROJECT VERSION 4.0

#=================================================================================

from tkinter import *
import tkinter.messagebox as tm
import smtplib,random,string,datetime,time




class LoginFrame(Frame):
    def __init__(self, master, title="LOGIN"):
        
        super().__init__(master)
        root.title("Welcome to EMAIL BOMBER")
        
        self.label_username = Label(self, text="\t Enter Your Email")
        self.label_password = Label(self, text="\t OTP you get")
        self.label_vnm = Label(self, text="\t Victim's Name")
        self.label_vic = Label(self, text="\t Victim's Email")
        self.label_num = Label(self, text="\t No. of mail (Max 50)")

        self.label_Declaration = Label(self, text="     DO THIS FOR FUN, NOT FOR REVENGE.\t",bg="white")
        self.label_blank = Label(self, text=" ")
        self.label_blank1 = Label(self, text="\t ")
        self.label_blank2 = Label(self, text="\t ")
        self.label_nl = Label(self, text=" \n ")
        self.label_nl1 = Label(self, text=" \t ")
        self.label_nl2 = Label(self, text=" \n ")

        self.entry_username = Entry(self)
        self.entry_password = Entry(self, show="*")
        self.entry_vnm = Entry(self)
        self.entry_vic = Entry(self)
        self.entry_num = Entry(self)
        
        
        self.label_nl.grid(row=0, column =1)
        self.label_blank.grid(row=3, column =2)
        self.label_Declaration.grid(row=2,column =1, columnspan=2)
        self.label_username.grid(row=4, column=1,  sticky = E)
        self.label_password.grid(row=5, column=1, sticky=E)
        self.entry_username.grid(row=4, column=2)

        self.label_vnm.grid(row=6, column=1, sticky=E)
        self.entry_vnm.grid(row=6, column=2, padx=100)

        self.label_vic.grid(row=7, column=1, sticky=E)
        self.entry_vic.grid(row=7, column=2, padx=100)

        self.label_num.grid(row=8, column=1, sticky=E)
        self.entry_num.grid(row=8, column=2, padx=100)
        
        self.label_blank1.grid(row=4, column =3)
        self.entry_password.grid(row=5, column=2)

        self.checkbox = Checkbutton(self, text="I HEREBY READ AND ACCEPT ALL T&Cs OF EMAIL BOMBER.",fg='green',command=self._check_btn_clicked)
        self.checkbox.grid(row=10, column=2)

        self.label_blank2.grid(row=9, column =2)
        self.label_nl1.grid(row=11, column=2, columnspan=2)

        self.logbtn = Button(self, text="  BOMB MAIL  ", fg='red',command=self._login_btn_clicked, state=DISABLED)
        self.logbtn.grid(row=12, column=2, columnspan=2)
        self.label_nl2.grid(row=9, column=2, columnspan=2)
        self.otpbtn = Button(self, text= "  Send OTP  ", fg='green',command=self._otp_btn_clicked, state=DISABLED)
        self.otpbtn.grid(row=12, column=1, columnspan=2)
        self.helpbtn = Button(self, text= "  HELP and T&Cs  ",fg='blue', command=self._help_btn_clicked)
        self.helpbtn.grid(row=12, column=0, columnspan=2 )
        self.label_nl2.grid(row=13, column=2, columnspan=2)

        self.pack()

    def _help_btn_clicked(self):
        tm.showinfo("HELP and T&Cs","\nWelcome to Email BOMBER.\n\nBy using this service, you can spam your friend's mailbox by some autogenerated mails. Now, lets see how can you use EMAIL BOMBER.\n\nTo use EMAIL BOMBER, please follow the following steps:\n\n 1. Enter your email address.\n 2. READ and ACCEPT ALL TERMs & CONDITIONs. \n 3. Press SEND OTP button.\n 4. Check your email inbox and enter your OTP.\n 5. Fill out details of your Victim.[remember No. of mails < 50].\n 6. Now, just press BOMB MAIL and you are good to go.\n\nTERMS AND CONDITIONS OF USING EMAIL BOMBER\n\n 1. User must be atleast 18 years old.\n 2. DON'T SPAM unknown/stranger using Email Bomber. \n 3. DO it for FUN, NOT for revenge. \n 4. EMAIL BOMBER DOESN'T take any responsibility on the casuality, caused by this service. User will be responsible for his/her each and every work, using EMAIL BOMBER. Also, EMAIL BOMBER MAY collect some user data using this app.\n 5. User can use this service only 3 times freely using one email address. BEYOND that limit, his/her email address MAY be blocked for future use on Email Bomber.\n\n THANK YOU FOR USING EMAIL BOMBER. \n\n Created by Amlan, 2019")

    def _check_btn_clicked(self):
        self.otpbtn.configure(state=NORMAL)
        
    def _otp_btn_clicked(self):
        # print("Clicked")
        mail = self.entry_username.get()
        if len(mail) == 0:
            tm.showerror("OOPS", "Your Email address cann't be empty. \nPlease enter your VALID email.")
            
        else:   

            #self.logbtn.configure(state=NORMAL)
            try:
                #SERVER LOGIN--------------------------------------------------
                server = smtplib.SMTP('smtp.gmail.com',587)
                server.ehlo()
                server.starttls()
                server.ehlo()

                server.login('YOURMAIL','P@s$w0rD')

                #OTP MAIL GENERATION-------------------------------------------

                otp = [891872, 701565, 363563, 907353, 624209, 130687, 989153, 494930, 819293, 425905, 648354, 855622, 301326, 226462, 873547, 541724, 318725, 903516, 272045, 833316, 119908, 534203, 908608, 652123, 678809, 913742, 803596, 661437, 913054, 745096, 162281, 345673, 553551, 456307, 819893, 587213, 762050, 888458, 298501, 923013, 229874, 923619, 424781, 878507, 993003, 667262, 216649, 263074, 448738, 103316, 820226, 797047, 175055, 609206, 349881, 641109, 650546, 181557, 596569, 179502, 258144, 735545, 559948, 326902, 756171, 671684, 997005, 584206, 277439, 734508, 452476, 131266, 892148, 327095, 915870, 794384, 370810, 486159, 444204, 567343, 952003, 115921, 492855, 833748, 938155, 969733, 623716, 189156, 826083, 111506, 459581, 574404, 550128, 549516, 561761, 426479, 280488, 840580, 261705, 251918, 566767]

                sub = "OTP for Email Bomber"
                k = random.randint(0,100)
                otpsend = otp[k]
                doby = "\n Your OTP for Email Bomber is :"+str(otpsend)+". Thank you for using our service."

                #OTP SEND-------------------------------------------------------
                subject = sub
                body = doby

                msg = f"Subject: {subject} \n\n {body}"

                server.sendmail(
                    'YOURMAIL',
                    mail,
                    msg
                )
                self.logbtn.configure(state=NORMAL)
                tm.showinfo("YUPPY", "OTP has been sent to your mail address successfully. \n Please check your mail.")
            except:
                tm.showerror("OOPS", "Error in Network Connection or Incorrect email address. \n Please Check again and continue.")
                

    def _login_btn_clicked(self):
        # print("Clicked")
        vic = self.entry_vic.get()
        vnm = self.entry_vnm.get()
        num = self.entry_num.get()
        val = self.entry_password.get()
        mail = self.entry_username.get()
        uid = random.randint(10,99)

        
        otp = [891872, 701565, 363563, 907353, 624209, 130687, 989153, 494930, 819293, 425905, 648354, 855622, 301326, 226462, 873547, 541724, 318725, 903516, 272045, 833316, 119908, 534203, 908608, 652123, 678809, 913742, 803596, 661437, 913054, 745096, 162281, 345673, 553551, 456307, 819893, 587213, 762050, 888458, 298501, 923013, 229874, 923619, 424781, 878507, 993003, 667262, 216649, 263074, 448738, 103316, 820226, 797047, 175055, 609206, 349881, 641109, 650546, 181557, 596569, 179502, 258144, 735545, 559948, 326902, 756171, 671684, 997005, 584206, 277439, 734508, 452476, 131266, 892148, 327095, 915870, 794384, 370810, 486159, 444204, 567343, 952003, 115921, 492855, 833748, 938155, 969733, 623716, 189156, 826083, 111506, 459581, 574404, 550128, 549516, 561761, 426479, 280488, 840580, 261705, 251918, 566767]

        flag = 0
        for i in range(0,100):
            otpval = otp[i]
            if str(otpval) == val:
                flag = 1
                break
            else:
                continue
        if flag == 1:
            tm.showinfo("HOORRAY","OTP Verification is Successful.")


            if int(num)<51:
                tm.showinfo("HOORRAY","FIRING UP OUR SERVER. NOW BOMBING YOUR VICTIM.")
      
                try:
                    def randomString(stringLength):
                        letters = string.ascii_lowercase
                        return ''.join(random.choice(letters) for i in range(stringLength))

                    sub = randomString(32)
                    doby = "Hello "+str(vnm)+"!\nYou have an Encrypted Message from our user. \n[UserID : CXU249568"+str(uid)+"].\n\nYour ENCRYPTED MESSAGE is :\n\n"+randomString(1024)+"\n\nKEY : "+randomString(120)+str(random.randint(10000000,99999999))+"\n\nThank you for using our 512-bit Encryption System.\n\n\n"

                    #SENDING PART-----------------------------------------------------------
                    server = smtplib.SMTP('smtp.gmail.com',587)
                    server.ehlo()
                    server.starttls()
                    server.ehlo()

                    server.login('YOURMAIL','P@s$w0rD')
                    n = 1
                    while n <= int(num):
                        subject = sub+"::P: "+str(n)
                        body = doby
                        
                        msg = f"Subject: {subject} \n\n {body}"

                        server.sendmail(
                            'YOURMAIL',
                            vic,
                            msg
                        )
                        if n==1:
                            tm.showinfo("YUPPY","FIRST MAIL HAS BEEN SENT SUCCESSFULLY. NOW SENDING NEXT ONE ...")
                        elif n==10 and int(num)>10:
                            tm.showinfo("YUPPY","10 MAILs HAVE BEEN SENT SUCCESSFULLY. MORE TO GO :)")
                        n = n+1
                        
                    except:
                        tm.showerror("OOPS", "Server Failure or Error in Network Connection.\nPlease try again after some time.\nError Code: EX400000D3")

            else:

                tm.showerror("OOPS", "Please agree all T&Cs. Check that MAX no. of mails must not exceed 50 and then continue.")
                    



            #time.sleep(3)
            #tm.showerror("OOPS", "Server Failure or Error in Network Connection.\nPlease try again after some time.\nError Code: EX400000D3")
            
        else:
            tm.showerror("OOPS", "You have entered WRONG OTP.\n Please check your OTP and try again.")
            


root = Tk()
lf = LoginFrame(root)
root.mainloop()
